# 通用配置文件

app:
  host: "0.0.0.0:8082"
  log_level: "debug"
  debug: true
  max_request: 1000

mongo:
  uri: "mongodb://127.0.0.1:27017"
  dbname: "book"
  max_open: 10 # 最大链接数
  time_out: 300 # 超时 毫秒

